server:
  port: 8300
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.110.228.214:3306/cloudnote
    username: root
    password: 9*2Xi;:akcf1